services:
  code_container:
    extends:
      service: service_base
    image: mcr.microsoft.com/devcontainers/base:bullseye
    container_name: ${SERVICE_NAME}_code
    tty: true
    command: sh
    volumes:
      - sync_data:/${SERVICE_NAME}:rw
  code_sync:
    image: alpine:latest
    container_name: ${SERVICE_NAME}_sync
    tty: true
    volumes:
      - sync_data:/${SERVICE_NAME}:rwo
  service_base:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    env_file:
      - .env
    networks:
      - devcontainer_network_alias
networks:
  devcontainer_network_alias:
    name: ${SERVICE_NAME}_network
    driver: bridge
volumes:
  sync_data:
  unison: 
